void sys_putchar(int sysno, int c);
void sys_getc(int sysno);
void sys_getenvid(int sysno);
void sys_yield();
void sys_env_destroy(int sysno, u32 envid);
void sys_set_pgfault_handler(int sysno, int envid, u64 func, u64 xstacktop);
void sys_mem_alloc(int sysno, u32 envid, u64 va, u64 perm);
void sys_mem_map(int sysno, u32 srcid, u64 srcva, u32 dstid, u64 dstva, u64 perm);
void sys_mem_unmap(int sysno, u32 envid, u64 va);
void sys_env_alloc(int sysno);
void sys_set_env_status(int sysno, u32 envid, u32 status);
void sys_set_trapframe(int sysno, u32 envid, struct Trapframe *tf);
void sys_panic(int sysno, char *msg);
void sys_ipc_recv(int sysno, u64 dstva);
void sys_ipc_can_send(int sysno, u32 envid, u32 value, u64 srcva, u64 perm);
void sys_get_envs(int sysno);
void sys_write_sd(int, u64*, u32);
void sys_read_sd(int, u64*, u32);
void sys_get_pageref(int, u32);